### ISSUE TITLE
USER STORY: Add products  

### ISSUE THREAD

**Issue by Kristaal** [Kristaal/ecommerce-website#12]
As an **owner** I can **add new products to the store** so that **we can sell more items to our customers**

### Acceptance Criteria
- The owner should be able to add products from the front end without relying on the backend features.

### Tasks
- [ ] Add items button
- [ ] Add items functionality
- [ ] Add items views
