### ISSUE TITLE
USER STORY: Remove products

### ISSUE THREAD

**Issue by Kristaal** [Kristaal/ecommerce-website#13]
As an **owner** I can **remove items from the store** so that **customers no longer see items I do not intend to sell again**

### Acceptance Criteria
- The owner should be able to remove items completely from the store

### Tasks
- [ ] remove items button
- [ ] remove items functionality
- [ ] remove items views
