### ISSUE TITLE
USER STORY: Edit products

### ISSUE THREAD

**Issue by Kristaal** [Kristaal/ecommerce-website#14]
As an **owner** I can **edit products** so that **products have the correct information and/or pricing**

### Acceptance Criteria
- The owner should be able to edit products on the live site without needing to update on the backend

### Tasks
- [x] edit item button
- [x] edit items functionality 
- [x] edit items views
