### ISSUE TITLE
USER STORY: Create account

### ISSUE THREAD

**Issue by Kristaal** [Kristaal/ecommerce-website#5]
As a **user** I can **easily register for an account** so that **I can have a personal account and be able to view my profile**

### Acceptance Criteria
- This story will be completed when a new user can sign up to the website. 
- The user should not be able to view or access the admin panel of the website. 
- The user should be logged in to an account that is unique to them.

### Tasks
- [x] Install Django-Allauth   
- [x] Create Template 
- [x] Create logic 
- [x] Registration link
- [x] Registration form
- [x] Test Create account
- [x] Test user accessing admin panel
