### ISSUE TITLE
USER STORY: Login and logout 

### ISSUE THREAD

**Issue by Kristaal** [Kristaal/ecommerce-website#6]
As a **user** I can **login and logout** so that **I can access my personal account information**

### Acceptance Criteria
- This story will be completed when a  user can  proceed to login and logout with their personal information.

### Tasks
- [x] Login / Logout pages     
- [x] Login / Logout links    
- [x] Test login / logout
